"""
VectorStoreComponent — Dependency-Injected Vector Index
========================================================
Manages the vector store for RAG retrieval. Currently supports:

- **Qdrant** (embedded local mode or remote server)
- **Simple** (in-memory NumPy — for development/testing)

Provides a unified interface for:
- Adding documents with embeddings + metadata
- Similarity search (top-k nearest neighbours)
- Collection management (create, delete, list)

All embeddings are generated by the injected EmbeddingComponent,
ensuring consistency across ingest and retrieval.
"""
from __future__ import annotations

import hashlib
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

from settings import VectorStoreSettings

logger = logging.getLogger("forsa.components.vector_store")


@dataclass
class VectorDocument:
    """A document stored in the vector index."""

    doc_id: str
    text: str
    embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    score: float = 0.0


class VectorStoreComponent:
    """
    Injectable vector store component.

    Supports both Qdrant (recommended for production) and a simple
    in-memory fallback for development.
    """

    def __init__(
        self,
        settings: VectorStoreSettings,
        embedding_component: Any,  # EmbeddingComponent — Any to avoid circular import
    ) -> None:
        self._settings = settings
        self._embedding = embedding_component
        self._client: Any = None
        self._provider = settings.provider.lower()
        self._initialise()

    def _initialise(self) -> None:
        if self._provider == "qdrant":
            self._init_qdrant()
        elif self._provider == "simple":
            self._init_simple()
        else:
            raise ValueError(f"Unknown vector store provider: {self._provider}")

    # ------------------------------------------------------------------
    # Qdrant Backend
    # ------------------------------------------------------------------

    def _init_qdrant(self) -> None:
        logger.info("VectorStoreComponent: Initialising Qdrant …")
        t0 = time.perf_counter()

        from qdrant_client import QdrantClient
        from qdrant_client.models import Distance, VectorParams

        if self._settings.qdrant_url:
            self._client = QdrantClient(url=self._settings.qdrant_url)
            logger.info("  Connected to Qdrant server at %s", self._settings.qdrant_url)
        else:
            storage_path = Path(self._settings.qdrant_path)
            storage_path.mkdir(parents=True, exist_ok=True)
            self._client = QdrantClient(path=str(storage_path))
            logger.info("  Using Qdrant embedded mode at %s", storage_path)

        # Ensure collection exists
        collections = [c.name for c in self._client.get_collections().collections]
        if self._settings.collection_name not in collections:
            self._client.create_collection(
                collection_name=self._settings.collection_name,
                vectors_config=VectorParams(
                    size=self._embedding.dimension,
                    distance=Distance.COSINE,
                ),
            )
            logger.info(
                "  Created collection '%s' (dim=%d)",
                self._settings.collection_name,
                self._embedding.dimension,
            )
        else:
            logger.info(
                "  Collection '%s' already exists",
                self._settings.collection_name,
            )

        elapsed = time.perf_counter() - t0
        logger.info("VectorStoreComponent: Qdrant ready in %.1fs", elapsed)

    # ------------------------------------------------------------------
    # Simple In-Memory Backend
    # ------------------------------------------------------------------

    def _init_simple(self) -> None:
        logger.info("VectorStoreComponent: Using simple in-memory store")
        self._client = {
            "documents": [],  # List[VectorDocument]
            "embeddings": None,  # np.ndarray or None
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def is_ready(self) -> bool:
        return self._client is not None

    @property
    def collection_name(self) -> str:
        return self._settings.collection_name

    def add_documents(
        self,
        documents: List[VectorDocument],
        batch_size: int = 64,
    ) -> int:
        """
        Add documents to the vector store.

        Embeddings are generated automatically if not already present.
        Returns the number of documents successfully added.
        """
        if not documents:
            return 0

        # Generate embeddings for documents that don't have them
        texts_to_embed = []
        indices_to_embed = []
        for i, doc in enumerate(documents):
            if doc.embedding is None:
                texts_to_embed.append(doc.text)
                indices_to_embed.append(i)

        if texts_to_embed:
            embeddings = self._embedding.embed_texts(texts_to_embed)
            for idx, emb in zip(indices_to_embed, embeddings):
                documents[idx].embedding = emb

        if self._provider == "qdrant":
            return self._qdrant_add(documents, batch_size)
        else:
            return self._simple_add(documents)

    def search(
        self,
        query: str,
        top_k: int = 5,
        filter_metadata: Optional[Dict[str, Any]] = None,
    ) -> List[VectorDocument]:
        """
        Search for documents most similar to the query.

        Returns up to ``top_k`` VectorDocument results sorted by score
        (highest first).
        """
        query_embedding = self._embedding.embed_text(query)

        if self._provider == "qdrant":
            return self._qdrant_search(query_embedding, top_k, filter_metadata)
        else:
            return self._simple_search(query_embedding, top_k)

    def count(self) -> int:
        """Return the number of documents in the collection."""
        if self._provider == "qdrant":
            info = self._client.get_collection(self._settings.collection_name)
            return info.points_count
        else:
            return len(self._client["documents"])

    def delete_collection(self) -> None:
        """Delete the entire collection (use with caution)."""
        if self._provider == "qdrant":
            self._client.delete_collection(self._settings.collection_name)
            logger.info("Deleted Qdrant collection '%s'", self._settings.collection_name)
        else:
            self._client["documents"] = []
            self._client["embeddings"] = None
            logger.info("Cleared in-memory vector store")

    # ------------------------------------------------------------------
    # Qdrant Implementation
    # ------------------------------------------------------------------

    def _qdrant_add(self, documents: List[VectorDocument], batch_size: int) -> int:
        from qdrant_client.models import PointStruct

        points = []
        for doc in documents:
            point_id = hashlib.md5(doc.doc_id.encode()).hexdigest()
            # Qdrant requires integer or UUID point IDs
            int_id = int(point_id[:16], 16) & 0x7FFFFFFFFFFFFFFF
            points.append(
                PointStruct(
                    id=int_id,
                    vector=doc.embedding,
                    payload={
                        "doc_id": doc.doc_id,
                        "text": doc.text[:10000],  # Truncate for storage
                        **doc.metadata,
                    },
                )
            )

        # Batch upsert
        for i in range(0, len(points), batch_size):
            batch = points[i : i + batch_size]
            self._client.upsert(
                collection_name=self._settings.collection_name,
                points=batch,
            )

        logger.info("Added %d documents to Qdrant", len(points))
        return len(points)

    def _qdrant_search(
        self,
        query_embedding: List[float],
        top_k: int,
        filter_metadata: Optional[Dict] = None,
    ) -> List[VectorDocument]:
        from qdrant_client.models import Filter, FieldCondition, MatchValue

        query_filter = None
        if filter_metadata:
            conditions = [
                FieldCondition(key=k, match=MatchValue(value=v))
                for k, v in filter_metadata.items()
            ]
            query_filter = Filter(must=conditions)

        results = self._client.search(
            collection_name=self._settings.collection_name,
            query_vector=query_embedding,
            limit=top_k,
            query_filter=query_filter,
        )

        documents = []
        for hit in results:
            payload = hit.payload or {}
            documents.append(
                VectorDocument(
                    doc_id=payload.get("doc_id", str(hit.id)),
                    text=payload.get("text", ""),
                    score=hit.score,
                    metadata={
                        k: v
                        for k, v in payload.items()
                        if k not in ("doc_id", "text")
                    },
                )
            )
        return documents

    # ------------------------------------------------------------------
    # Simple In-Memory Implementation
    # ------------------------------------------------------------------

    def _simple_add(self, documents: List[VectorDocument]) -> int:
        self._client["documents"].extend(documents)
        # Rebuild embedding matrix
        all_embs = [d.embedding for d in self._client["documents"]]
        self._client["embeddings"] = np.array(all_embs, dtype="float32")
        logger.info("Added %d documents to in-memory store", len(documents))
        return len(documents)

    def _simple_search(
        self,
        query_embedding: List[float],
        top_k: int,
    ) -> List[VectorDocument]:
        if not self._client["documents"]:
            return []

        q_vec = np.array(query_embedding, dtype="float32")
        emb_matrix = self._client["embeddings"]

        # Cosine similarity (embeddings are already normalised)
        scores = emb_matrix @ q_vec
        top_indices = np.argsort(scores)[::-1][:top_k]

        results = []
        for idx in top_indices:
            doc = self._client["documents"][idx]
            results.append(
                VectorDocument(
                    doc_id=doc.doc_id,
                    text=doc.text,
                    score=float(scores[idx]),
                    metadata=doc.metadata,
                )
            )
        return results
